### ISSUE TITLE
mate-terminal-1.15.1 Segmentation fault

### ISSUE THREAD

**Issue by dpblnt** [Sabayon/mate-overlay#87]
(gdb) run
Starting program: /usr/bin/mate-terminal 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffeb83d700 (LWP 12950)]
[New Thread 0x7fffeb03c700 (LWP 12951)]
[New Thread 0x7fffea83b700 (LWP 12952)]
[New Thread 0x7fffe95f7700 (LWP 12953)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5f5b59f in g_type_check_instance_is_a () from /usr/lib64/libgobject-2.0.so.0
(gdb) backtrace
#0  0x00007ffff5f5b59f in g_type_check_instance_is_a () from /usr/lib64/libgobject-2.0.so.0
#1  0x00007ffff7392e16 in gtk_widget_get_parent () from /usr/lib64/libgtk-3.so.0
#2  0x00000000004266e7 in ?? ()
#3  0x00007ffff5f37f75 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#4  0x00007ffff5f4a2c1 in ?? () from /usr/lib64/libgobject-2.0.so.0
#5  0x00007ffff5f52d65 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#6  0x00007ffff5f52fc7 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#7  0x00007ffff5f3c654 in ?? () from /usr/lib64/libgobject-2.0.so.0
#8  0x00007ffff5f3bebe in ?? () from /usr/lib64/libgobject-2.0.so.0
#9  0x00007ffff5f3ec3b in g_object_thaw_notify () from /usr/lib64/libgobject-2.0.so.0
#10 0x00007ffff7991f11 in ?? () from /usr/lib64/libvte-2.91.so.0
#11 0x00007ffff79924c8 in ?? () from /usr/lib64/libvte-2.91.so.0
#12 0x00007ffff79971a3 in ?? () from /usr/lib64/libvte-2.91.so.0
#13 0x00007ffff5c39643 in ?? () from /usr/lib64/libglib-2.0.so.0
#14 0x00007ffff5c38bad in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#15 0x00007ffff5c38f80 in ?? () from /usr/lib64/libglib-2.0.so.0
#16 0x00007ffff5c392a2 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#17 0x00007ffff7250d85 in gtk_main () from /usr/lib64/libgtk-3.so.0
#18 0x0000000000412fce in ?? ()
#19 0x00007ffff51157b0 in __libc_start_main () from /lib64/libc.so.6
#20 0x0000000000413109 in ?? ()
(gdb) quit

On gentoo using the following package versions
gcc: x86_64-pc-linux-gnu-4.9.3
x11-libs/gtk+-3.18.9
dev-libs/glib-2.46.2-r3

Steps to reproduce:
1. open mate-terminal
2. open new tab
3. detach new tab
4. in new tab type: sudo su -
or ssh localhost

**Comment by dpblnt** [comment]
sorry, not Sabayon related
